--- #YAML:1.0
name:               podlinkcheck
version:            11
abstract:           Check POD L<> link references.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant::defer:      0
    File::Find::Iterator:  0
    File::Spec:           0.8
    File::Temp:           0
    IPC::Run:             0
    List::Util:           0
    Locale::TextDomain:   0
    perl:                 5.006
    Pod::Find:            0
    Pod::Simple:          0
    Test::More:           0
resources:
    homepage:  http://user42.tuxfamily.org/podlinkcheck/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - xt
        - devel
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_interoperation:
        description:  Have maximum inter-operation with other modules (optional supported other stuff).
        requires:
            CPANPLUS::Backend:    0
            CPANPLUS::Configure:  0
            Sort::Key::Natural:   0
recommends:
    Sort::Key::Natural:  0
